stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: search-engine

containerization:
  stage: containerization
  script:
    - cp ${SECRETS} ./secrets.js
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    # create/update the deployment
    - envsubst < deployment.yml | kubectl apply -f -
    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
