stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: neo4j-search-engine
  DEPLOYMENT_NAME: search-engine
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

containerization:
  stage: containerization
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deployment:
  stage: deployment
  script:
    # create/update the deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
