apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      containers:
      - name: ${DEPLOYMENT_NAME}
        image: ${CONTAINER_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from secret
        env:
        - name: NODES
          value: Employee,Workplace,Computer,Group
        - name: PROPERTIES
          value: name,email_address,display_name,name_kanji,name_katakana,username
        envFrom:
        - secretRef:
           name: environment-variables

---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  ports:
  - port: 80
    nodePort: 30086
  selector:
    app: ${DEPLOYMENT_NAME}
  type: NodePort
